# Generated by Django 4.2 on 2025-10-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0002_studentlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentList',
        ),
    ]
