# Generated by Django 4.2 on 2025-12-01 09:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0004_classroom_examday_examschedule_semester_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seatallocation',
            options={'ordering': ('exam_schedule__exam_day__date', 'classroom__id', 'bench_number', 'seat_side')},
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='examschedule',
            name='end_time',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examschedule',
            name='start_time',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seatallocation',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seatallocation',
            name='seat_side',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('S', 'Single')], default='L', max_length=1),
        ),
        migrations.AddField(
            model_name='seatallocation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seatallocation',
            name='exam_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='seating.examschedule'),
        ),
        migrations.AlterUniqueTogether(
            name='seatallocation',
            unique_together={('exam_schedule', 'classroom', 'bench_number', 'seat_side')},
        ),
    ]
